package com.example.padresdinamicos

import android.content.Intent
import android.os.Bundle
import androidx.activity.enableEdgeToEdge
import androidx.lifecycle.lifecycleScope
import androidx.recyclerview.widget.LinearLayoutManager
import com.example.padresdinamicos.adapters.RecyclerSubcategoryAdapter
import com.example.padresdinamicos.databinding.ActivityMenuBinding
import com.example.padresdinamicos.databinding.ActivityUserScreenBinding
import com.example.padresdinamicos.dataclasses.Recipe
import com.example.padresdinamicos.dataclasses.Subcategory
import com.example.padresdinamicos.room.RecipeDatabase
import com.example.padresdinamicos.room.RecipeDatabase.Companion.getDatabase
import com.google.gson.Gson
import kotlinx.coroutines.launch

class MenuActivity : BaseActivity() {
    private lateinit var binding: ActivityMenuBinding
    private val recyclerSubcategoryAdapter by lazy { RecyclerSubcategoryAdapter() }
    private lateinit var dbAccess : RecipeDatabase

    companion object {
        val ID_PASO_RECETA = "ID_PASO_RECETA"
        val ID_PASO_SUBCATEGORIA = "ID_PASO_SUBCATEGORIA"
    }
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMenuBinding.inflate(layoutInflater)
        val view = binding.root
        enableEdgeToEdge()
        setContentView(view)


        dbAccess = getDatabase(this)

        lifecycleScope.launch {
            if (dbAccess.recipeDao().obtenerTodasLasRecetas().isEmpty()){
                val recipes = listOf(
                    Recipe(name = "Pasta Carbonara", image = R.drawable.pastacarbonara, category =  "Paises", subcategory1 = "Italia", subcategory2 = "Platos Principales", ingredients = arrayListOf("Spaguetti", "Tocino", "Parmesano", "Huevo"), dificulty = "Fácil", time = "20 min", quantity = "2 personas", amount = arrayListOf("200g", "100g", "50g", "2 unidades")),
                    Recipe(name = "Pizza Margarita", image = R.drawable.pizzamargarita, category =  "Paises", subcategory1 = "Italia", subcategory2 = "Platos Principales", ingredients = arrayListOf("Masa", "Tomate", "Mozzarella", "Albahaca"), dificulty = "Media", time = "30 min", quantity = "4 personas", amount = arrayListOf("1 base", "150g", "200g", "10 hojas")),
                    Recipe(name = "Lasagna", image = R.drawable.lasagna, category =  "Paises", subcategory1 = "Italia", subcategory2 = "Platos Principales", ingredients = arrayListOf("Pasta", "Carne", "Queso", "Tomate"), dificulty = "Difícil", time = "1 h", quantity = "6 personas", amount = arrayListOf("200g", "300g", "200g", "300g")),
                    Recipe(name = "Risotto al pesto", image = R.drawable.risottoalpesto, category =  "Paises", subcategory1 = "Italia", subcategory2 = "Platos Principales", ingredients = arrayListOf("Arroz", "Pescado", "Pesto", "Ajo"), dificulty = "Media", time = "45 min", quantity = "4 personas", amount = arrayListOf("200g", "150g", "100g", "2 dientes")),
                    Recipe(name = "Tiramisu", image = R.drawable.tiramisu, category =  "Paises", subcategory1 = "Italia", subcategory2 = "Postres", ingredients = arrayListOf("Masa", "Chocolate", "Leche", "Canela"), dificulty = "Media", time = "3 h", quantity = "8 personas", amount = arrayListOf("200g", "100g", "500ml", "1 cucharada")),
                    Recipe(name = "Tacos al Pastor", image = R.drawable.tacosalpastor, category =  "Paises", subcategory1 = "México", subcategory2 = "Entradas", ingredients = arrayListOf("Tortilla", "Carne al Pastor", "Cilantro", "Cebolla", "Piña"), dificulty = "Fácil", time = "20 min", quantity = "4 personas", amount = arrayListOf("8 unidades", "300g", "50g", "50g", "100g")),
                    Recipe(name = "Enchiladas Verdes", image = R.drawable.enchiladasverdes, category =  "Paises", subcategory1 = "México", subcategory2 = "Alta en Proteína", ingredients = arrayListOf("Tortillas", "Salsa verde", "Pollo", "Cebolla","Crema"), dificulty = "Media", time = "40 min", quantity = "6 personas", amount = arrayListOf("12 unidades", "300ml", "300g", "50g", "100g")),
                    Recipe(name = "Guacamole", image = R.drawable.guacamole, category =  "Paises", subcategory1 = "México", subcategory2 = "Vegana", ingredients = arrayListOf("Aguacate", "Tomate", "Cebolla", "Cilantro", "Lima"), dificulty = "Fácil", time = "10 min", quantity = "4 personas", amount = arrayListOf("2 unidades", "100g", "50g", "10g", "1 unidad")),
                    Recipe(name = "Chiles Rellenos", image = R.drawable.chilesrellenos, category =  "Paises", subcategory1 = "México", subcategory2 = "Frituras", ingredients = arrayListOf("Chile poblano", "Carne molida", "Queso", "Salsa"), dificulty = "Media", time = "1 h", quantity = "4 personas", amount = arrayListOf("4 unidades", "200g", "100g", "200ml")),
                    Recipe(name = "Pozole", image = R.drawable.pozole, category = "Paises", subcategory1 = "México", subcategory2 = "Pozole", ingredients = arrayListOf("Maíz hominy", "Carne de cerdo o pollo", "Ajo", "Cebolla", "Orégano", "Chile en polvo", "Limón", "Rábanos", "Lechuga"), dificulty = "Media", time = "2 h", quantity = "6 personas", amount = arrayListOf("500g", "400g", "2 dientes", "100g", "5g", "10g", "2 unidades", "50g", "100g")),
                    Recipe(name = "Sushi (Maki Rolls)", image = R.drawable.sushi, category = "Japón", subcategory1 = "Japón", subcategory2 = "Sushi", ingredients = arrayListOf("Arroz para sushi", "Alga nori", "Pescado crudo (salmón o atún)", "Pepino", "Aguacate", "Vinagre de arroz", "Azúcar", "Sal"), dificulty = "Media", time = "1 h", quantity = "4 personas", amount = arrayListOf("200g", "4 hojas", "100g", "50g", "50g", "30ml", "10g", "5g")),
                    Recipe(name = "Ramen", image = R.drawable.ramen, category = "Japón", subcategory1 = "Japón", subcategory2 = "Ramen", ingredients = arrayListOf("Fideos de ramen", "Caldo de pollo o cerdo", "Salsa de soja", "Huevo cocido", "Cebollines", "Alga nori", "Chashu (carne de cerdo)"), dificulty = "Media", time = "1 h", quantity = "2 personas", amount = arrayListOf("200g", "500ml", "50ml", "2 unidades", "50g", "1 hoja", "100g")),
                    Recipe(name = "Tempura", image = R.drawable.tempura, category = "Japón", subcategory1 = "Japón", subcategory2 = "Tempura", ingredients = arrayListOf("Mariscos (camarones, calamares)", "Verduras (zanahoria, calabacín, berenjena)", "Harina de trigo", "Huevo", "Agua fría", "Aceite para freír"), dificulty = "Media", time = "30 min", quantity = "4 personas", amount = arrayListOf("200g", "200g", "100g", "1 unidad", "200ml", "500ml")),
                    Recipe(name = "Okonomiyaki", image = R.drawable.okonomiyaki, category = "Japón", subcategory1 = "Japón", subcategory2 = "Okonomiyaki", ingredients = arrayListOf("Harina de trigo", "Huevo", "Col rallada", "Cebollín", "Tocino o cerdo", "Salsa okonomiyaki", "Mayonesa japonesa", "Katsuobushi (copos de bonito seco)"), dificulty = "Media", time = "40 min", quantity = "4 personas", amount = arrayListOf("200g", "2 unidades", "200g", "50g", "100g", "50ml", "50ml", "10g")),
                    Recipe(name = "Dorayaki", image = R.drawable.dorayaki, category = "Japón", subcategory1 = "Japón", subcategory2 = "Dorayaki", ingredients = arrayListOf("Harina de trigo", "Huevo", "Azúcar", "Miel", "Pasta de frijol rojo (anko)", "Bicarbonato de sodio"), dificulty = "Fácil", time = "30 min", quantity = "4 personas", amount = arrayListOf("200g", "2 unidades", "100g", "50g", "150g", "5g")),
                    Recipe(name = "Silpancho", image = R.drawable.silpancho, category = "Bolivia", subcategory1 = "Bolivia", subcategory2 = "Silpancho", ingredients = arrayListOf("Carne de res", "Arroz", "Papa", "Huevo", "Cebolla", "Tomate"), dificulty = "Media", time = "1 h", quantity = "4 personas", amount = arrayListOf("200g", "200g", "200g", "2 unidades", "50g", "50g")),
                    Recipe(name = "Plato Paceño", image = R.drawable.platopaceno, category = "Bolivia", subcategory1 = "Bolivia", subcategory2 = "Plato Paceño", ingredients = arrayListOf("Arroz", "Papa", "Carne de res", "Chicharrón", "Salsa de maní"), dificulty = "Media", time = "1 h", quantity = "4 personas", amount = arrayListOf("200g", "200g", "200g", "100g", "50ml")),
                    Recipe(name = "Majadito", image = R.drawable.majadito, category = "Bolivia", subcategory1 = "Bolivia", subcategory2 = "Majadito", ingredients = arrayListOf("Arroz", "Carne de res", "Plátano", "Huevo", "Verduras"), dificulty = "Media", time = "50 min", quantity = "4 personas", amount = arrayListOf("200g", "200g", "1 unidad", "2 unidades", "100g")),
                    Recipe(name = "Sopa de Maní", image = R.drawable.sopademani, category = "Bolivia", subcategory1 = "Bolivia", subcategory2 = "Sopa", ingredients = arrayListOf("Maní", "Carne de res", "Papa", "Fideos", "Verduras"), dificulty = "Media", time = "1 h", quantity = "6 personas", amount = arrayListOf("100g", "200g", "200g", "100g", "200g")),
                    Recipe(name = "Pique a lo Macho", image = R.drawable.piquealomacho, category = "Bolivia", subcategory1 = "Bolivia", subcategory2 = "Pique a lo Macho", ingredients = arrayListOf("Carne de res", "Papa", "Cebolla", "Tomate", "Ají rojo"), dificulty = "Media", time = "1 h", quantity = "4 personas", amount = arrayListOf("300g", "200g", "100g", "50g", "10g")),
                    Recipe(name = "Quiche Lorraine", image = R.drawable.quichelorraine, category = "Francia", subcategory1 = "Francia", subcategory2 = "Quiche Lorraine", ingredients = arrayListOf("Masa quebrada", "Huevo", "Crema de leche", "Bacon", "Queso Gruyère", "Cebolla", "Pimienta"), dificulty = "Media", time = "60 min", quantity = "6 porciones", amount = arrayListOf("1 masa", "3 huevos", "200 ml", "150 g", "100 g", "1 cebolla", "al gusto")),
                    Recipe(name = "Ratatouille", image = R.drawable.ratatouille, category = "Paises", subcategory1 = "Francia", subcategory2 = "Ratatouille", ingredients = arrayListOf("Berenjena", "Calabacín", "Pimiento rojo", "Tomate", "Cebolla", "Ajo", "Aceite de oliva", "Hierbas provenzales"), dificulty = "Fácil", time = "50 min", quantity = "4 porciones", amount = arrayListOf("1", "1", "1", "3", "1", "2 dientes", "50 ml", "al gusto")),
                    Recipe(name = "Soupe à l'Oignon", image = R.drawable.soupeaioignon, category = "Francia", subcategory1 = "Francia", subcategory2 = "Soupe à l'Oignon", ingredients = arrayListOf("Cebolla", "Caldo de carne", "Vino blanco", "Pan", "Queso Gruyère", "Mantequilla", "Harina"), dificulty = "Media", time = "45 min", quantity = "4 porciones", amount = arrayListOf("3 cebollas", "500 ml", "100 ml", "4 rebanadas", "100 g", "50 g", "2 cucharadas")),
                    Recipe(name = "Croissant", image = R.drawable.croissant, category = "Francia", subcategory1 = "Francia",subcategory2 =  "Desayunos", ingredients = arrayListOf("Harina", "Mantequilla", "Levadura", "Leche", "Azúcar", "Sal", "Huevos"), dificulty = "Difícil", time = "180 min", quantity = "12 croissants", amount = arrayListOf("500 g", "250 g", "15 g", "250 ml", "50 g", "10 g", "2")),
                    Recipe(name = "Crème Brûlée", image = R.drawable.cremebrulee, category = "Francia", subcategory1 = "Francia", subcategory2 = "Postre", ingredients = arrayListOf("Yemas de huevo", "Crema de leche", "Azúcar", "Vainilla", "Azúcar moreno (para caramelizar)"), dificulty = "Media", time = "40 min", quantity = "4 porciones", amount = arrayListOf("4", "500 ml", "100 g", "1 vaina", "50 g")),
                    Recipe(name = "Pancakes", image = R.drawable.pancakes, category = "Tipo de comida", subcategory1 = "Desayunos", subcategory2 = "Pancakes", ingredients = arrayListOf("Harina", "Leche", "Huevo", "Azúcar", "Mantequilla", "Polvo de hornear", "Miel", "Frutas (opcional)"), dificulty = "Fácil", time = "20 min", quantity = "6 pancakes", amount = arrayListOf("200 g", "250 ml", "1", "30 g", "30 g", "10 g", "al gusto", "al gusto")),
                    Recipe(name = "Smoothie Bowl", image = R.drawable.smoothiebowl, category = "Tipo de comida", subcategory1 = "Desayunos", subcategory2 = "Smoothie Bowl", ingredients = arrayListOf("Frutas congeladas", "Leche o yogur", "Granola", "Semillas", "Frutas frescas", "Miel"), dificulty = "Fácil", time = "10 min", quantity = "1 porción", amount = arrayListOf("200 g", "100 ml", "50 g", "10 g", "50 g", "al gusto")),
                    Recipe(name = "Huevos Benedictinos", image = R.drawable.huevosbenedictino, category = "Tipo de comida", subcategory1 = "Desayunos", subcategory2 = "Huevos Benedictinos", ingredients = arrayListOf("Huevos", "Pan tostado", "Jamón", "Salsa holandesa", "Vinagre", "Sal", "Pimienta"), dificulty = "Media", time = "30 min", quantity = "2 porciones", amount = arrayListOf("2", "2 rebanadas", "2 lonjas", "100 ml", "1 cucharada", "al gusto", "al gusto")),
                    Recipe(name = "Avena con Frutas", image = R.drawable.avenaconfrutas, category = "Tipo de comida", subcategory1 = "Desayunos", subcategory2 = "Avena con Frutas", ingredients = arrayListOf("Avena", "Leche", "Miel", "Frutas (plátano, fresas, arándanos)", "Frutos secos"), dificulty = "Fácil", time = "15 min", quantity = "1 porción", amount = arrayListOf("50 g", "200 ml", "al gusto", "100 g", "20 g")),
                    Recipe(name = "Tostadas de Aguacate", image = R.drawable.tostadasdeaguacate, category = "Tipo de comida", subcategory1 = "Desayunos", subcategory2 = "Tostadas de Aguacate", ingredients = arrayListOf("Pan integral", "Aguacate", "Huevo", "Sal", "Pimienta", "Aceite de oliva"), dificulty = "Fácil", time = "10 min", quantity = "1 porción", amount = arrayListOf("2 rebanadas", "1", "1", "al gusto", "al gusto", "1 cucharadita")),
                    Recipe(name = "Bruschettas", image = R.drawable.bruschettas, category = "Tipo de comida", subcategory1 = "Entradas", subcategory2 = "Bruschettas", ingredients = arrayListOf("Pan baguette", "Tomate", "Albahaca", "Ajo", "Aceite de oliva", "Vinagre balsámico"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "15 minutos", quantity = "4 personas", amount = arrayListOf("1 pan baguette", "2 tomates", "1 rama de albahaca", "2 dientes de ajo", "3 cucharadas de aceite de oliva", "1 cucharada de vinagre balsámico")),
                    Recipe(name = "Hummus con Pita", image = R.drawable.hummusconpita, category = "Tipo de comida", subcategory1 = "Entradas", subcategory2 = "Hummus con Pita", ingredients = arrayListOf("Garbanzos", "Tahini", "Ajo", "Limón", "Aceite de oliva", "Pita"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "20 minutos", quantity = "4 personas", amount = arrayListOf("1 taza de garbanzos cocidos", "2 cucharadas de tahini", "1 diente de ajo", "1 limón", "3 cucharadas de aceite de oliva", "1 pan pita")),
                    Recipe(name = "Sopa de Tomate", image = R.drawable.sopadetomate, category = "Tipo de comida", subcategory1 = "Entradas", subcategory2 = "Sopa de Tomate", ingredients = arrayListOf("Tomates", "Cebolla", "Ajo", "Caldo de pollo", "Aceite de oliva", "Sal", "Pimienta"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "30 minutos", quantity = "4 personas", amount = arrayListOf("4 tomListates", "1 cebolla", "2 dientes de ajo", "2 tazas de caldo de pollo", "2 cucharadas de aceite de oliva", "Sal y pimienta al gusto")),
                    Recipe(name = "Calamares Fritos", image = R.drawable.calamaresfritos, category = "Tipo de comida", subcategory1 = "Entradas", subcategory2 = "Calamares Fritos", ingredients = arrayListOf("Calamares", "Harina", "Sal", "Pimienta", "Aceite para freír", "Limón"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "25 minutos", quantity = "4 personas", amount = arrayListOf("500g de calamares", "1 taza de harina", "Sal y pimienta al gusto", "Aceite para freír", "1 limón")),
                    Recipe(name = "Tabule", image = R.drawable.tabule, category = "Tipo de comida", subcategory1 = "Entradas", subcategory2 = "Tabule", ingredients = arrayListOf("Trigo bulgur", "Perejil", "Tomate", "Pepino", "Cebolla", "Menta", "Jugo de limón", "Aceite de oliva"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "15 minutos", quantity = "4 personas", amount = arrayListOf("1 taza de trigo bulgur", "1 taza de perejil picado", "2 tomates", "1 pepino", "1 cebolla", "Hoja de menta", "Jugo de 1 limón", "2 cucharadas de aceite de oliva")),
                    Recipe(name = "Pollo al Curry", image = R.drawable.polloalcurry, category = "Tipo de comida", subcategory1 = "Plato Principal", subcategory2 = "Pollo al Curry", ingredients = arrayListOf("Pollo", "Curry en polvo", "Cebolla", "Ajo", "Leche de coco", "Tomate", "Aceite de oliva", "Arroz"), isFavorite = false, isCreatedByUser = false, dificulty = "Alta", time = "45 minutos", quantity = "4 personas", amount = arrayListOf("4 piezas de pollo", "2 cucharadas de curry en polvo", "1 cebolla", "2 dientes de ajo", "1 taza de leche de coco", "2 tomates", "2 cucharadas de aceite de oliva", "1 taza de arroz")),
                    Recipe(name = "Espagueti Boloñesa", image = R.drawable.spaguettibolognesa, category = "Tipo de comida", subcategory1 = "Plato Principal", subcategory2 = "Espagueti Boloñesa", ingredients = arrayListOf("Espagueti", "Carne molida de res", "Tomate", "Cebolla", "Ajo", "Aceite de oliva", "Pasta de tomate", "Vino tinto"), isFavorite = false, isCreatedByUser = false, dificulty = "Alta", time = "1 hora", quantity = "4 personas", amount = arrayListOf("500g de espagueti", "500g de carne molida de res", "2 tomates", "1 cebolla", "2 dientes de ajo", "2 cucharadas de aceite de oliva", "3 cucharadas de pasta de tomate", "1/4 taza de vino tinto")),
                    Recipe(name = "Estofado de Res", image = R.drawable.estofadoderes, category = "Tipo de comida", subcategory1 = "Plato Principal", subcategory2 = "Estofado de Res", ingredients = arrayListOf("Carne de res", "Zanahoria", "Papa", "Cebolla", "Ajo", "Caldo de res", "Pimiento", "Laurel", "Aceite de oliva"), isFavorite = false, isCreatedByUser = false, dificulty = "Alta", time = "2 horas", quantity = "6 personas", amount = arrayListOf("1 kg de carne de res", "2 zanahorias", "4 papas", "1 cebolla", "2 dientes de ajo", "2 tazas de caldo de res", "1 pimiento", "2 hojas de laurel", "2 cucharadas de aceite de oliva")),
                    Recipe(name = "Paella", image = R.drawable.paella, category = "Plato Principal", subcategory1 = "Plato Principal", subcategory2 = "Paella", ingredients = arrayListOf("Arroz", "Mariscos", "Pollo", "Pimiento", "Guisante", "Tomate", "Caldo de pollo", "Azafrán", "Aceite de oliva"), isFavorite = false, isCreatedByUser = false, dificulty = "Alta", time = "1 hora", quantity = "6 personas", amount = arrayListOf("2 tazas de arroz", "500g de mariscos", "500g de pollo", "1 pimiento", "1 taza de guisantes", "2 tomates", "4 tazas de caldo de pollo", "1 cucharadita de azafrán", "3 cucharadas de aceite de oliva")),
                    Recipe(name = "Salmón a la Plancha", image = R.drawable.salmonalaplancha, category = "Plato Principal", subcategory1 = "Plato Principal", subcategory2 = "Salmón a la Plancha", ingredients = arrayListOf("Salmón", "Aceite de oliva", "Limón", "Ajo", "Pimienta", "Sal", "Perejil"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "20 minutos", quantity = "4 personas", amount = arrayListOf("4 filetes de salmón", "3 cucharadas de aceite de oliva", "1 limón", "2 dientes de ajo", "Sal y pimienta al gusto", "Perejil al gusto")),
                    Recipe(name = "Cheesecake", image = R.drawable.chesesecake, category = "Postres", subcategory1 = "Postres", subcategory2 = "Cheesecake", ingredients = arrayListOf("Galletas Digestive", "Queso crema", "Azúcar", "Huevos", "Crema de leche", "Esencia de vainilla", "Mantequilla"), dificulty = "Media", time = "1 hora", quantity = "8 porciones", amount = arrayListOf("200g", "400g", "150g", "3", "200ml", "1 cdta", "100g")),
                    Recipe(name = "Brownies", image = R.drawable.brownie, category = "Postres", subcategory1 = "Postres", subcategory2 = "Brownies", ingredients = arrayListOf("Harina", "Chocolate", "Azúcar", "Mantequilla", "Huevos", "Nueces", "Esencia de vainilla"), dificulty = "Fácil", time = "40 min", quantity = "12 porciones", amount = arrayListOf("120g", "200g", "150g", "100g", "3", "50g", "1 cdta")),
                    Recipe(name = "Arroz con Leche", image = R.drawable.arrozconleche, category = "Postres", subcategory1 = "Postres", subcategory2 = "Arroz con Leche", ingredients = arrayListOf("Arroz", "Leche", "Azúcar", "Canela", "Cáscara de limón", "Esencia de vainilla"), dificulty = "Fácil", time = "50 min", quantity = "6 porciones", amount = arrayListOf("100g", "1L", "100g", "1 rama", "1", "1 cdta")),
                    Recipe(name = "Flan", image = R.drawable.flan, category = "Postres", subcategory1 = "Postres", subcategory2 = "Flan", ingredients = arrayListOf("Leche", "Azúcar", "Huevos", "Esencia de vainilla", "Caramelo"), dificulty = "Media", time = "1 hora", quantity = "8 porciones", amount = arrayListOf("500ml", "150g", "4", "1 cdta", "100g")),
                    Recipe(name = "Churros", image = R.drawable.churros, category = "Postres", subcategory1 = "Postres", subcategory2 = "Churros", ingredients = arrayListOf("Harina", "Agua", "Azúcar", "Sal", "Aceite", "Canela", "Chocolate para mojar"), dificulty = "Media", time = "45 min", quantity = "20 unidades", amount = arrayListOf("200g", "250ml", "50g", "1 pizca", "Para freír", "1 cdta", "100g")),
                    Recipe(name = "Mojito", image = R.drawable.mojito, category = "Bebidas", subcategory1 = "Bebidas", subcategory2 = "Mojito", ingredients = arrayListOf("Ron blanco", "Menta", "Azúcar", "Limón", "Agua con gas", "Hielo"), dificulty = "Fácil", time = "10 min", quantity = "1 vaso", amount = arrayListOf("50ml", "10 hojas", "2 cdas", "1", "100ml", "Al gusto")),
                    Recipe(name = "Margarita", image = R.drawable.margarita, category = "Bebidas", subcategory1 = "Bebidas", subcategory2 = "Margarita", ingredients = arrayListOf("Tequila", "Triple sec", "Jugo de lima", "Sal", "Hielo"), dificulty = "Fácil", time = "10 min", quantity = "1 vaso", amount = arrayListOf("50ml", "25ml", "25ml", "Al gusto", "Al gusto")),
                    Recipe(name = "Té Matcha", image = R.drawable.matchate, category = "Bebidas", subcategory1 = "Bebidas", subcategory2 = "Té Matcha", ingredients = arrayListOf("Té matcha", "Leche", "Azúcar", "Hielo"), dificulty = "Fácil", time = "5 min", quantity = "1 vaso", amount = arrayListOf("1 cdta", "200ml", "1 cda", "Al gusto")),
                    Recipe(name = "Batido de Fresa", image = R.drawable.batidodefresa, category = "Bebidas", subcategory1 = "Bebidas", subcategory2 = "Batido de Fresa", ingredients = arrayListOf("Fresas", "Leche", "Yogur", "Miel", "Hielo"), dificulty = "Fácil", time = "10 min", quantity = "1 vaso", amount = arrayListOf("150g", "200ml", "50g", "1 cda", "Al gusto")),
                    Recipe(name = "Horchata", image = R.drawable.horchata, category = "Bebidas", subcategory1 = "Bebidas", subcategory2 = "Horchata", ingredients = arrayListOf("Arroz", "Canela", "Azúcar", "Leche", "Vainilla", "Hielo"), dificulty = "Fácil", time = "1 hora", quantity = "1L", amount = arrayListOf("100g", "1 rama", "100g", "500ml", "1 cdta", "Al gusto")),
                    Recipe(name = "Ensalada Caprese", image = R.drawable.ensaladacapresse, category = "Estilo de Alimentación", subcategory1 = "Vegetariana", subcategory2 = "Ensalada Caprese", ingredients = arrayListOf("Tomate", "Mozzarella", "Albahaca", "Aceite de oliva", "Vinagre balsámico"), dificulty = "Fácil", time = "10 min", quantity = "2 porciones", amount = arrayListOf("2", "200g", "10 hojas", "2 cdas", "1 cda")),
                    Recipe(name = "Curry de Garbanzos", image = R.drawable.currydegarbanzos, category = "Estilo de Alimentación", subcategory1 = "Vegetariana", subcategory2 = "Curry de Garbanzos", ingredients = arrayListOf("Garbanzos", "Cebolla", "Ajo", "Jengibre", "Curry en polvo", "Leche de coco", "Espinaca"), dificulty = "Media", time = "30 min", quantity = "4 porciones", amount = arrayListOf("400g", "1", "2 dientes", "1 cda", "2 cdas", "200ml", "100g")),
                    Recipe(name = "Hamburguesa de Lentejas", image = R.drawable.hamburguesadelentejas, category = "Estilo de Alimentación", subcategory1 = "Vegetariana", subcategory2 = "Hamburguesa de Lentejas", ingredients = arrayListOf("Lentejas", "Ajo", "Cebolla", "Pan rallado", "Especias", "Lechuga", "Tomate"), dificulty = "Media", time = "40 min", quantity = "6 unidades", amount = arrayListOf("200g", "2 dientes", "1", "50g", "Al gusto", "4 hojas", "1")),
                    Recipe(name = "Risotto de Champiñones", image = R.drawable.rissotodechampinones, category = "Estilo de Alimentación", subcategory1 = "Vegetariana", subcategory2 = "Risotto de Champiñones", ingredients = arrayListOf("Arroz arborio", "Champiñones", "Caldo vegetal", "Cebolla", "Vino blanco", "Queso parmesano"), dificulty = "Alta", time = "1 hora", quantity = "4 porciones", amount = arrayListOf("300g", "200g", "1L", "1", "100ml", "50g")),
                    Recipe(name = "Ratatouille", image = R.drawable.ratatouille, category = "Estilo de Alimentación", subcategory1 = "Vegetariana", subcategory2 = "Ratatouille", ingredients = arrayListOf("Berenjena", "Calabacín", "Tomate", "Pimiento", "Cebolla", "Ajo", "Aceite de oliva"), dificulty = "Media", time = "1 hora", quantity = "4 porciones", amount = arrayListOf("1", "1", "2", "1", "1", "2 dientes", "2 cdas")),
                    Recipe(name = "Tacos de Soya", image = R.drawable.tacosdesoya, category = "Estilo de Alimentación", subcategory1 = "Vegana", subcategory2 = "Tacos de Soya", ingredients = arrayListOf("Soya texturizada", "Tortillas de maíz", "Cebolla", "Aguacate", "Limón", "Cilantro", "Salsa"), dificulty = "Fácil", time = "20 min", quantity = "4 tacos", amount = arrayListOf("200g", "4", "1", "1", "1", "Al gusto", "Al gusto")),
                    Recipe(name = "Smoothie Verde", image = R.drawable.smoothieverde, category = "Estilo de Alimentación", subcategory1 = "Vegana", subcategory2 = "Smoothie Verde", ingredients = arrayListOf("Espinaca", "Plátano", "Leche de almendra", "Semillas de chía", "Miel"), dificulty = "Fácil", time = "10 min", quantity = "1 vaso", amount = arrayListOf("100g", "1", "200ml", "1 cda", "1 cda")),
                    Recipe(name = "Pasta con Salsa de Anacardos", image = R.drawable.pastaconsalsadeanacardos, category = "Estilo de Alimentación", subcategory1 = "Vegana", subcategory2 = "Pasta con Salsa de Anacardos", ingredients = arrayListOf("Pasta", "Anacardos", "Ajo", "Leche de coco", "Limón", "Pimienta"), dificulty = "Media", time = "30 min", quantity = "2 porciones", amount = arrayListOf("200g", "100g", "2 dientes", "100ml", "1", "Al gusto")),
                    Recipe(name = "Brownies Veganos", image = R.drawable.browniesveganos, category = "Estilo de Alimentación", subcategory1 = "Vegana", subcategory2 = "Brownies Veganos", ingredients = arrayListOf("Harina de avena", "Cacao", "Plátano", "Leche de almendra", "Polvo de hornear", "Nueces"), dificulty = "Fácil", time = "40 min", quantity = "12 unidades", amount = arrayListOf("120g", "50g", "1", "100ml", "1 cdta", "50g")),
                    Recipe(name = "Helado de Plátano", image = R.drawable.heladodeplatano, category = "Estilo de Alimentación", subcategory1 = "Vegana", subcategory2 = "Helado de Plátano", ingredients = arrayListOf("Plátanos", "Leche de almendra", "Extracto de vainilla"), dificulty = "Fácil", time = "2 horas", quantity = "4 porciones", amount = arrayListOf("4", "100ml", "1 cdta")),
                    Recipe(name = "Pizza de Coliflor", image = R.drawable.pizzadecoliflor, category = "Estilo de Alimentación", subcategory1 = "Sin Gluten", subcategory2 = "Italia", ingredients = arrayListOf("Coliflor", "Huevo", "Queso mozzarella", "Tomate", "Albahaca", "Aceite de oliva"), isFavorite = false, isCreatedByUser = false, dificulty = "Alta", time = "45 minutos", quantity = "4 personas", amount = arrayListOf("1 coliflor", "1 huevo", "200g de queso mozzarella", "2 tomates", "1 rama de albahaca", "2 cucharadas de aceite de oliva")),
                    Recipe(name = "Ensalada Griega", image = R.drawable.ensaladagriega, category = "Estilo de Alimentación", subcategory1 = "Sin Gluten", subcategory2 = "Vegetariana", ingredients = arrayListOf("Pepino", "Tomate", "Aceitunas", "Feta", "Cebolla roja", "Aceite de oliva", "Limón"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "15 minutos", quantity = "4 personas", amount = arrayListOf("1 pepino", "2 tomates", "1 taza de aceitunas", "150g de queso feta", "1 cebolla roja", "2 cucharadas de aceite de oliva", "Jugo de 1 limón")),
                    Recipe(name = "Pollo a la Parrilla con Vegetales", image = R.drawable.polloalaparillaconvegetales, category = "Estilo de Alimentación", subcategory1 = "Sin Gluten", subcategory2 = "Pollo a la Parrilla con Vegetales", ingredients = arrayListOf("Pechuga de pollo", "Zanahorias", "Calabacín", "Aceite de oliva", "Especias"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "30 minutos", quantity = "4 personas", amount = arrayListOf("4 pechugas de pollo", "2 zanahorias", "2 calabacines", "2 cucharadas de aceite de oliva", "Especias al gusto")),
                    Recipe(name = "Sopa de Lentejas", image = R.drawable.sopadelentejas, category = "Estilo de Alimentación", subcategory1 = "Sin Gluten", subcategory2 = "Sopa de Lentejas", ingredients = arrayListOf("Lentejas", "Cebolla", "Ajo", "Tomate", "Zanahorias", "Caldo de verduras"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "1 hora", quantity = "4 personas", amount = arrayListOf("1 taza de lentejas", "1 cebolla", "2 dientes de ajo", "2 tomates", "2 zanahorias", "4 tazas de caldo de verduras")),
                    Recipe(name = "Bizcocho de Almendra", image = R.drawable.bizcochodealmnedras, category = "Estilo de Alimentación", subcategory1 = "Sin Gluten", subcategory2 = "Bizcocho de Almendra", ingredients = arrayListOf("Harina de almendra", "Huevo", "Miel", "Aceite de coco", "Levadura en polvo"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "40 minutos", quantity = "8 porciones", amount = arrayListOf("2 tazas de harina de almendra", "3 huevos", "1/4 taza de miel", "1/4 taza de aceite de coco", "1 cucharadita de levadura en polvo")),
                    Recipe(name = "Zoodles con Pesto", image = R.drawable.zoodlesconpesto, category = "Estilo de Alimentación", subcategory1 = "Low Carb", subcategory2 = "Zoodles con Pesto", ingredients = arrayListOf("Calabacín", "Albahaca", "Ajo", "Piñones", "Aceite de oliva", "Parmesano"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "20 minutos", quantity = "4 personas", amount = arrayListOf("2 calabacines", "1 taza de albahaca", "1 diente de ajo", "1/4 taza de piñones", "2 cucharadas de aceite de oliva", "1/4 taza de queso parmesano")),
                    Recipe(name = "Pollo a la Mostaza", image = R.drawable.polloalamostaza, category = "Estilo de Alimentación", subcategory1 = "Low Carb", subcategory2 = "Pollo a la Mostaza", ingredients = arrayListOf("Pechuga de pollo", "Mostaza", "Miel", "Ajo", "Aceite de oliva"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "30 minutos", quantity = "4 personas", amount = arrayListOf("4 pechugas de pollo", "2 cucharadas de mostaza", "1 cucharada de miel", "2 dientes de ajo", "2 cucharadas de aceite de oliva")),
                    Recipe(name = "Ensalada César sin Croutons", image = R.drawable.ensaladacesarsincroutons, category = "Estilo de Alimentación", subcategory1 = "Low Carb", subcategory2 = "Ensalada César sin Croutons", ingredients = arrayListOf("Lechuga", "Pollo a la parrilla", "Aderezo César", "Queso parmesano", "Aceite de oliva"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "15 minutos", quantity = "4 personas", amount = arrayListOf("1 lechuga romana", "2 pechugas de pollo a la parrilla", "Aderezo César al gusto", "1/4 taza de queso parmesano", "2 cucharadas de aceite de oliva")),
                    Recipe(name = "Tacos de Lechuga", image = R.drawable.tacosdelechuga, category = "Estilo de Alimentación", subcategory1 = "Low Carb", subcategory2 = "Tacos de Lechuga", ingredients = arrayListOf("Carne molida", "Lechuga", "Tomate", "Cebolla", "Salsa"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "20 minutos", quantity = "4 personas", amount = arrayListOf("500g de carne molida", "1 lechuga", "2 tomates", "1 cebolla", "Salsa al gusto")),
                    Recipe(name = "Cheesecake Keto", image = R.drawable.chessecakeketo, category = "Estilo de Alimentación", subcategory1 = "Low Carb", subcategory2 = "Cheesecake Keto", ingredients = arrayListOf("Queso crema", "Harina de almendra", "Mantequilla", "Edulcorante", "Extracto de vainilla"), isFavorite = false, isCreatedByUser = false, dificulty = "Alta", time = "1 hora", quantity = "8 porciones", amount = arrayListOf("500g de queso crema", "1 taza de harina de almendra", "1/4 taza de mantequilla", "Edulcorante al gusto", "1 cucharadita de extracto de vainilla")),
                    Recipe(name = "Pechuga de Pollo al Limón", image = R.drawable.pechugadepolloallimon, category = "Estilo de Alimentación", subcategory1 = "Alta en Proteína", subcategory2 = "Pechuga de Pollo al Limón", ingredients = arrayListOf("Pechuga de pollo", "Limón", "Ajo", "Aceite de oliva", "Pimienta"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "25 minutos", quantity = "4 personas", amount = arrayListOf("4 pechugas de pollo", "1 limón", "2 dientes de ajo", "2 cucharadas de aceite de oliva", "Sal y pimienta al gusto")),
                    Recipe(name = "Tortilla de Claras con Espinaca", image = R.drawable.torillasdeclara, category = "Estilo de Alimentación", subcategory1 = "Alta en Proteína", subcategory2 = "Tortilla de Claras con Espinaca", ingredients = arrayListOf("Claras de huevo", "Espinaca", "Cebolla", "Tomate", "Aceite de oliva"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "15 minutos", quantity = "2 personas", amount = arrayListOf("6 claras de huevo", "1 taza de espinaca", "1/2 cebolla", "1 tomate", "1 cucharada de aceite de oliva")),
                    Recipe(name = "Salmón con Salsa Teriyaki", image = R.drawable.salmonconsalsateriyaki, category = "Estilo de Alimentación", subcategory1 = "Alta en Proteína", subcategory2 = "Salmón con Salsa Teriyaki", ingredients = arrayListOf("Salmón", "Salsa teriyaki", "Ajo", "Jengibre", "Cebollín"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "20 minutos", quantity = "4 personas", amount = arrayListOf("4 filetes de salmón", "3 cucharadas de salsa teriyaki", "1 diente de ajo", "1 trozo pequeño de jengibre", "Cebollín al gusto")),
                    Recipe(name = "Batido de Proteína", image = R.drawable.batidodeproteina, category = "Estilo de Alimentación", subcategory1 = "Alta en Proteína", subcategory2 = "Bebidas", ingredients = arrayListOf("Proteína en polvo", "Leche de almendra", "Plátano", "Espinaca", "Semillas de chía"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "10 minutos", quantity = "1 persona", amount = arrayListOf("1 scoop de proteína en polvo", "1 taza de leche de almendra", "1 plátano", "1/2 taza de espinaca", "1 cucharada de semillas de chía")),
                    Recipe(name = "Albóndigas al Horno", image = R.drawable.albondigasalhorno, category = "Estilo de Alimentación", subcategory1 = "Alta en Proteína", subcategory2 = "Albóndigas al Horno", ingredients = arrayListOf("Carne de res", "Huevo", "Pan rallado", "Ajo", "Pimienta", "Tomate"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "40 minutos", quantity = "4 personas", amount = arrayListOf("500g de carne de res", "1 huevo", "1/2 taza de pan rallado", "2 dientes de ajo", "Pimienta al gusto", "1 tomate")),
                    Recipe(name = "Lasagna", image = R.drawable.lasagna, category = "Método de Preparación", subcategory1 = "Al Horno", subcategory2 = "Lasagna", ingredients = arrayListOf("Pasta de lasaña", "Carne molida", "Salsa bechamel", "Queso mozzarella", "Tomate", "Cebolla", "Ajo"), isFavorite = false, isCreatedByUser = false, dificulty = "Alta", time = "1.5 horas", quantity = "6 personas", amount = arrayListOf("12 láminas de pasta de lasaña", "500g de carne molida", "2 tazas de salsa bechamel", "200g de queso mozzarella", "2 tomates", "1 cebolla", "2 dientes de ajo")),
                    Recipe(name = "Pollo Rostizado", image = R.drawable.pollorostizado, category = "Método de Preparación", subcategory1 = "Al Horno", subcategory2 = "Pollo Rostizado", ingredients = arrayListOf("Pollo entero", "Ajo", "Limón", "Romero", "Aceite de oliva", "Pimienta"), isFavorite = false, isCreatedByUser = false, dificulty = "Alta", time = "1.5 horas", quantity = "4 personas", amount = arrayListOf("1 pollo entero", "4 dientes de ajo", "1 limón", "Romero fresco", "2 cucharadas de aceite de oliva", "Sal y pimienta al gusto")),
                    Recipe(name = "Pan de Plátano", image = R.drawable.pandeplatano, category = "Método de Preparación", subcategory1 = "Al Horno", subcategory2 = "Pan de Plátano", ingredients = arrayListOf("Plátanos", "Harina", "Huevo", "Azúcar", "Bicarbonato de sodio", "Nueces"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "1 hora", quantity = "1 pan", amount = arrayListOf("3 plátanos maduros", "1 taza de harina", "2 huevos", "1/2 taza de azúcar", "1 cucharadita de bicarbonato de sodio", "1/4 taza de nueces")),
                    Recipe(name = "Pizza Casera", image = R.drawable.pizzacasera, category = "Método de Preparación", subcategory1 = "Al Horno", subcategory2 = "Pizza Casera", ingredients = arrayListOf("Masa para pizza", "Tomate", "Mozzarella", "Aceitunas", "Pepperoni", "Albahaca", "Aceite de oliva"), isFavorite = false, isCreatedByUser = false, dificulty = "Alta", time = "45 minutos", quantity = "2 personas", amount = arrayListOf("1 masa para pizza", "2 tomates", "200g de mozzarella", "Aceitunas al gusto", "100g de pepperoni", "Albahaca fresca", "2 cucharadas de aceite de oliva")),
                    Recipe(name = "Pescado en Papillote", image = R.drawable.pescadoenpapillote, category = "Método de Preparación", subcategory1 = "Al Horno", subcategory2 = "Platos Principales", ingredients = arrayListOf("Pescado blanco", "Ajo", "Limón", "Tomillo", "Aceite de oliva", "Papel aluminio"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "30 minutos", quantity = "4 personas", amount = arrayListOf("4 filetes de pescado blanco", "2 dientes de ajo", "1 limón", "Ramitas de tomillo", "2 cucharadas de aceite de oliva", "Papel aluminio")),
                    Recipe(name = "Costillas BBQ", image = R.drawable.costillasbbq, category = "Método de Preparación", subcategory1 = "A la Parrilla", subcategory2 = "Costillas BBQ", ingredients = arrayListOf("Costillas de cerdo", "Salsa BBQ", "Ajo", "Pimienta negra", "Aceite de oliva"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "1 hora", quantity = "4 personas", amount = arrayListOf("1 kg de costillas", "200 ml de salsa BBQ", "2 dientes de ajo", "1 cucharadita de pimienta negra", "2 cucharadas de aceite de oliva")),
                    Recipe(name = "Espárragos a la Parrilla", image = R.drawable.esparragosalaparilla, category = "Método de Preparación", subcategory1 = "A la Parrilla", subcategory2 = "Espárragos a la Parrilla", ingredients = arrayListOf("Espárragos", "Aceite de oliva", "Ajo", "Sal", "Pimienta"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "15 minutos", quantity = "2 personas", amount = arrayListOf("500 g de espárragos", "2 cucharadas de aceite de oliva", "2 dientes de ajo", "Sal al gusto", "Pimienta al gusto")),
                    Recipe(name = "Hamburguesas", image = R.drawable.hamburguesas, category = "Método de Preparación", subcategory1 = "A la Parrilla", subcategory2 = "Hamburguesas", ingredients = arrayListOf("Carne molida", "Pan de hamburguesa", "Lechuga", "Tomate", "Cebolla", "Queso", "Sal", "Pimienta"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "30 minutos", quantity = "4 personas", amount = arrayListOf("500 g de carne molida", "4 panes de hamburguesa", "4 hojas de lechuga", "2 tomates", "1 cebolla", "4 rebanadas de queso", "Sal y pimienta al gusto")),
                    Recipe(name = "Brochetas de Pollo", image = R.drawable.brochetasdepollo, category = "Método de Preparación", subcategory1 = "A la Parrilla", subcategory2 = "Brochetas de Pollo", ingredients = arrayListOf("Pechuga de pollo", "Pimientos", "Cebolla", "Aceite de oliva", "Especias"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "40 minutos", quantity = "4 personas", amount = arrayListOf("500 g de pechuga de pollo", "2 pimientos", "1 cebolla", "2 cucharadas de aceite de oliva", "Especias al gusto")),
                    Recipe(name = "Piña a la Parrilla", image = R.drawable.pinaalaparilla, category = "Método de Preparación", subcategory1 = "A la Parrilla", subcategory2 = "Piña a la Parrilla", ingredients = arrayListOf("Piña", "Azúcar moreno", "Canela", "Mantequilla"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "20 minutos", quantity = "2 personas", amount = arrayListOf("1 piña", "2 cucharadas de azúcar moreno", "1 cucharadita de canela", "2 cucharadas de mantequilla")),
                    Recipe(name = "Croquetas de Jamón", image = R.drawable.croquetasdejamon, category = "Método de Preparación", subcategory1 = "Frituras", subcategory2 = "Croquetas de Jamón", ingredients = arrayListOf("Jamón", "Harina", "Leche", "Huevo", "Pan rallado", "Mantequilla", "Pimienta"), isFavorite = false, isCreatedByUser = false, dificulty = "Alta", time = "45 minutos", quantity = "4 personas", amount = arrayListOf("200 g de jamón", "100 g de harina", "250 ml de leche", "1 huevo", "100 g de pan rallado", "50 g de mantequilla", "Pimienta al gusto")),
                    Recipe(name = "Papas Fritas", image = R.drawable.papasfritas, category = "Método de Preparación", subcategory1 = "Frituras", subcategory2 = "Papas Fritas", ingredients = arrayListOf("Papas", "Aceite para freír", "Sal"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "20 minutos", quantity = "2 personas", amount = arrayListOf("4 papas medianas", "Aceite suficiente", "Sal al gusto")),
                    Recipe(name = "Tempura de Verduras", image = R.drawable.tempuradeverduras, category = "Método de Preparación", subcategory1 = "Frituras", subcategory2 = "Tempura de Verduras", ingredients = arrayListOf("Calabacín", "Berenjena", "Pimientos", "Harina", "Huevo", "Agua fría", "Aceite para freír"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "30 minutos", quantity = "4 personas", amount = arrayListOf("1 calabacín", "1 berenjena", "1 pimiento", "100 g de harina", "1 huevo", "150 ml de agua fría", "Aceite suficiente")),
                    Recipe(name = "Pollo Frito", image = R.drawable.pollofrito, category = "Método de Preparación", subcategory1 = "Frituras", subcategory2 = "Pollo Frito", ingredients = arrayListOf("Pechuga de pollo", "Harina", "Huevo", "Aceite para freír", "Sal", "Pimienta"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "30 minutos", quantity = "4 personas", amount = arrayListOf("4 pechugas de pollo", "100 g de harina", "1 huevo", "Aceite suficiente", "Sal al gusto", "Pimienta al gusto")),
                    Recipe(name = "Donas", image = R.drawable.donas, category = "Método de Preparación", subcategory1 = "Frituras", subcategory2 = "Donas", ingredients = arrayListOf("Harina", "Levadura", "Leche", "Huevo", "Azúcar", "Mantequilla", "Aceite para freír"), isFavorite = false, isCreatedByUser = false, dificulty = "Alta", time = "1 hora", quantity = "10 donas", amount = arrayListOf("500 g de harina", "10 g de levadura", "200 ml de leche", "1 huevo", "100 g de azúcar", "100 g de mantequilla", "Aceite suficiente")),
                    Recipe(name = "Ceviche", image = R.drawable.ceviche, category = "Método de Preparación", subcategory1 = "En Crudo", subcategory2 = "Ceviche", ingredients = arrayListOf("Pescado fresco", "Cebolla morada", "Limón", "Cilantro", "Ají", "Sal", "Pimienta"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "30 minutos", quantity = "2 personas", amount = arrayListOf("300 g de pescado fresco", "1 cebolla morada", "4 limones", "Un puñado de cilantro", "1 ají", "Sal y pimienta al gusto")),
                    Recipe(name = "Tartare de Salmón", image = R.drawable.tartaredesalmon, category = "Método de Preparación", subcategory1 = "En Crudo", subcategory2 = "Tartare de Salmón", ingredients = arrayListOf("Salmón fresco", "Aguacate", "Cebollín", "Salsa de soja", "Aceite de oliva", "Jengibre"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "20 minutos", quantity = "2 personas", amount = arrayListOf("200 g de salmón fresco", "1 aguacate", "1 cebollín", "2 cucharadas de salsa de soja", "1 cucharada de aceite de oliva", "Un trozo pequeño de jengibre")),
                    Recipe(name = "Carpaccio de Res", image = R.drawable.carpaccioderes, category = "Método de Preparación", subcategory1 = "En Crudo", subcategory2 = "Carpaccio de Res", ingredients = arrayListOf("Carne de res", "Aceite de oliva", "Queso parmesano", "Rúcula", "Limón", "Sal", "Pimienta"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "15 minutos", quantity = "2 personas", amount = arrayListOf("200 g de carne de res", "2 cucharadas de aceite de oliva", "Queso parmesano al gusto", "Un puñado de rúcula", "1 limón", "Sal y pimienta al gusto")),
                    Recipe(name = "Ensalada Waldorf", image = R.drawable.ensaladawaldorf, category = "Método de Preparación", subcategory1 = "En Crudo", subcategory2 = "Ensalada Waldorf", ingredients = arrayListOf("Manzana", "Apio", "Nueces", "Uvas", "Yogur", "Mayonesa", "Limón"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "15 minutos", quantity = "2 personas", amount = arrayListOf("1 manzana", "1 rama de apio", "Un puñado de nueces", "Un puñado de uvas", "2 cucharadas de yogur", "1 cucharada de mayonesa", "1 cucharada de jugo de limón")),
                    Recipe(name = "Gazpacho", image = R.drawable.gazpacho, category = "Método de Preparación", subcategory1 = "En Crudo", subcategory2 = "Gazpacho", ingredients = arrayListOf("Tomate", "Pepino", "Pimiento", "Ajo", "Aceite de oliva", "Vinagre", "Pan", "Sal"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "20 minutos", quantity = "4 personas", amount = arrayListOf("4 tomates", "1 pepino", "1 pimiento", "2 dientes de ajo", "2 cucharadas de aceite de oliva", "2 cucharadas de vinagre", "1 rebanada de pan", "Sal al gusto")),
                    Recipe(name = "Chili con Carne", image = R.drawable.chilliconcarne, category = "Método de Preparación", subcategory1 = "Sopa", subcategory2 = "Chili con Carne", ingredients = arrayListOf("Carne molida", "Frijoles", "Tomate", "Cebolla", "Ajo", "Especias"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "1 hora", quantity = "4 personas", amount = arrayListOf("500 g de carne molida", "200 g de frijoles", "2 tomates", "1 cebolla", "2 dientes de ajo", "Especias al gusto")),
                    Recipe(name = "Sopa Minestrone", image = R.drawable.sopaminestrone, category = "Método de Preparación", subcategory1 = "Sopa", subcategory2 = "Sopa Minestrone", ingredients = arrayListOf("Pasta", "Verduras", "Caldo de verduras", "Tomate", "Ajo", "Albahaca"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "45 minutos", quantity = "4 personas", amount = arrayListOf("200 g de pasta", "Verduras variadas al gusto", "1 litro de caldo de verduras", "2 tomates", "2 dientes de ajo", "Albahaca fresca")),
                    Recipe(name = "Pho", image = R.drawable.pho, category = "Método de Preparación", subcategory1 = "Sopa", subcategory2 = "Pho", ingredients = arrayListOf("Fideos de arroz", "Caldo de res", "Hierbas frescas", "Limón", "Jengibre", "Salsa de soja"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "1 hora", quantity = "4 personas", amount = arrayListOf("200 g de fideos de arroz", "1 litro de caldo de res", "Hierbas frescas al gusto", "1 limón", "1 trozo de jengibre", "2 cucharadas de salsa de soja")),
                    Recipe(name = "Estofado de Ternera", image = R.drawable.estofadodeternera, category = "Método de Preparación", subcategory1 = "Sopa", subcategory2 = "Estofado de Ternera", ingredients = arrayListOf("Carne de ternera", "Zanahorias", "Papas", "Cebolla", "Ajo", "Caldo de res"), isFavorite = false, isCreatedByUser = false, dificulty = "Alta", time = "2 horas", quantity = "4 personas", amount = arrayListOf("1 kg de carne de ternera", "3 zanahorias", "3 papas", "1 cebolla", "3 dientes de ajo", "1 litro de caldo de res")),
                    Recipe(name = "Sopa de Pollo", image = R.drawable.sopadepollo, category = "Método de Preparación", subcategory1 = "Sopa", subcategory2 = "Sopa de Pollo", ingredients = arrayListOf("Pollo", "Zanahorias", "Apio", "Fideos", "Cebolla", "Ajo"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "1 hora", quantity = "4 personas", amount = arrayListOf("1 pollo entero", "3 zanahorias", "2 ramas de apio", "100 g de fideos", "1 cebolla", "2 dientes de ajo")),
                    Recipe(name = "Pastel de Chocolate", image = R.drawable.pasteldechocolate, category = "Evento", subcategory1 = "Cumpleaños", subcategory2 = "Postres", ingredients = arrayListOf("Harina", "Cacao en polvo", "Huevo", "Azúcar", "Leche", "Mantequilla", "Polvo de hornear"), isFavorite = false, isCreatedByUser = false, dificulty = "Alta", time = "1 hora", quantity = "8 personas", amount = arrayListOf("2 tazas de harina", "1 taza de cacao en polvo", "3 huevos", "1 taza de azúcar", "1 taza de leche", "1/2 taza de mantequilla", "1 cucharadita de polvo de hornear")),
                    Recipe(name = "Cupcakes Decorados", image = R.drawable.cupcakesdecorados, category = "Evento", subcategory1 = "Cumpleaños", subcategory2 = "Postres", ingredients = arrayListOf("Harina", "Huevo", "Azúcar", "Mantequilla", "Esencia de vainilla", "Glaseado"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "45 minutos", quantity = "12 cupcakes", amount = arrayListOf("1 taza de harina", "2 huevos", "1 taza de azúcar", "1/2 taza de mantequilla", "1 cucharadita de esencia de vainilla", "Glaseado al gusto")),
                    Recipe(name = "Croissants Rellenos", image = R.drawable.crossaintsrellenos, category = "Evento", subcategory1 = "Cumpleaños", subcategory2 = "Croissants Rellenos", ingredients = arrayListOf("Masa de hojaldre", "Jamón", "Queso", "Mantequilla", "Huevo"), isFavorite = false, isCreatedByUser = false, dificulty = "Alta", time = "1 hora", quantity = "8 croissants", amount = arrayListOf("1 paquete de masa de hojaldre", "200g de jamón", "200g de queso", "1/2 taza de mantequilla derretida", "1 huevo")),
                    Recipe(name = "Mini Pizzas", image = R.drawable.minipizzas, category = "Evento", subcategory1 = "Cumpleaños", subcategory2 = "Mini Pizzas", ingredients = arrayListOf("Masa para pizza", "Tomate", "Queso", "Pepperoni", "Albahaca"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "30 minutos", quantity = "4 mini pizzas", amount = arrayListOf("1 masa para pizza", "2 tomates", "200g de queso", "100g de pepperoni", "Albahaca al gusto")),
                    Recipe(name = "Sangría", image = R.drawable.sangria, category = "Evento", subcategory1 = "Cumpleaños", subcategory2 = "Sangría", ingredients = arrayListOf("Vino tinto", "Frutas (naranjas, manzanas)", "Brandy", "Azúcar", "Agua con gas"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "15 minutos", quantity = "6 personas", amount = arrayListOf("1 botella de vino tinto", "1 naranja", "1 manzana", "1/4 taza de brandy", "1/4 taza de azúcar", "2 tazas de agua con gas")),
                    Recipe(name = "Pavo Relleno", image = R.drawable.pavorelleno, category = "Evento", subcategory1 = "Navidad", subcategory2 = "Pavo Relleno", ingredients = arrayListOf("Pavo entero", "Pan rallado", "Cebolla", "Ajo", "Especias", "Caldo de pollo"), isFavorite = false, isCreatedByUser = false, dificulty = "Alta", time = "3 horas", quantity = "10 personas", amount = arrayListOf("1 pavo entero", "2 tazas de pan rallado", "1 cebolla", "2 dientes de ajo", "Especias al gusto", "1 taza de caldo de pollo")),
                    Recipe(name = "Ensalada Waldorf", image = R.drawable.ensaladawaldorf, category = "Evento", subcategory1 = "Navidad", subcategory2 = "Ensalada Waldorf", ingredients = arrayListOf("Manzana", "Apio", "Nueces", "Uvas", "Yogur", "Mayonesa"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "20 minutos", quantity = "4 personas", amount = arrayListOf("2 manzanas", "1 rama de apio", "1/2 taza de nueces", "1 taza de uvas", "1/2 taza de yogur", "3 cucharadas de mayonesa")),
                    Recipe(name = "Galletas de Jengibre", image = R.drawable.galletasdegengibre, category = "Evento", subcategory1 = "Navidad", subcategory2 = "Galletas de Jengibre", ingredients = arrayListOf("Harina", "Jengibre en polvo", "Canela", "Mantequilla", "Azúcar", "Huevo"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "1 hora", quantity = "24 galletas", amount = arrayListOf("2 tazas de harina", "1 cucharadita de jengibre en polvo", "1 cucharadita de canela", "1/2 taza de mantequilla", "1 taza de azúcar", "1 huevo")),
                    Recipe(name = "Ponche Navideño", image = R.drawable.ponchenavideno, category = "Evento", subcategory1 = "Navidad", subcategory2 = "Ponche Navideño", ingredients = arrayListOf("Leche", "Azúcar", "Clavo de olor", "Nuez moscada", "Huevos", "Ron"), isFavorite = false, isCreatedByUser = false, dificulty = "Alta", time = "45 minutos", quantity = "6 personas", amount = arrayListOf("2 tazas de leche", "1 taza de azúcar", "1/2 cucharadita de clavo de olor", "1/4 cucharadita de nuez moscada", "4 huevos", "1/4 taza de ron")),
                    Recipe(name = "Tronco de Navidad", image = R.drawable.tronconavideno, category = "Evento", subcategory1 = "Navidad", subcategory2 = "Tronco de Navidad", ingredients = arrayListOf("Bizcocho", "Mantequilla", "Cacao", "Crema de chocolate", "Azúcar"), isFavorite = false, isCreatedByUser = false, dificulty = "Alta", time = "2 horas", quantity = "8 personas", amount = arrayListOf("1 bizcocho", "1/2 taza de mantequilla", "1 taza de cacao", "1 taza de crema de chocolate", "1 taza de azúcar")),
                    Recipe(name = "Fresas Cubiertas de Chocolate", image = R.drawable.fresascubiertasdechocolate, category = "Evento", subcategory1 = "San Valentín", subcategory2 = "Postres", ingredients = arrayListOf("Fresas", "Chocolate negro", "Aceite de coco"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "30 minutos", quantity = "12 fresas", amount = arrayListOf("12 fresas", "200g de chocolate negro", "1 cucharadita de aceite de coco")),
                    Recipe(name = "Fondue de Queso", image = R.drawable.fonduedequeso, category = "Evento", subcategory1 = "San Valentín", subcategory2 = "Fondue de Queso", ingredients = arrayListOf("Queso suizo", "Vino blanco", "Ajo", "Pan", "Pimienta"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "30 minutos", quantity = "4 personas", amount = arrayListOf("200g de queso suizo", "1/2 taza de vino blanco", "1 diente de ajo", "Pan al gusto", "Pimienta al gusto")),
                    Recipe(name = "Raviolis en Salsa de Queso", image = R.drawable.raviolesensalsadequesos, category = "Evento", subcategory1 = "San Valentín", subcategory2 = "Raviolis en Salsa de Queso", ingredients = arrayListOf("Raviolis", "Queso crema", "Leche", "Ajo", "Mantequilla"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "40 minutos", quantity = "4 personas", amount = arrayListOf("400g de raviolis", "200g de queso crema", "1 taza de leche", "2 dientes de ajo", "2 cucharadas de mantequilla")),
                    Recipe(name = "Tarta de Fresas", image = R.drawable.tartadefresas, category = "Evento", subcategory1 = "San Valentín", subcategory2 = "Tarta de Fresas", ingredients = arrayListOf("Fresas", "Harina", "Azúcar", "Mantequilla", "Huevo", "Crema pastelera"), isFavorite = false, isCreatedByUser = false, dificulty = "Alta", time = "1 hora", quantity = "8 personas", amount = arrayListOf("300g de fresas", "1 taza de harina", "1 taza de azúcar", "1/2 taza de mantequilla", "2 huevos", "1 taza de crema pastelera")),
                    Recipe(name = "Martini de Frambuesa", image = R.drawable.martinideframbuesa, category = "Evento", subcategory1 = "San Valentín", subcategory2 = "Bebidas", ingredients = arrayListOf("Vodka", "Frambuesas", "Jugo de limón", "Azúcar"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "10 minutos", quantity = "2 copas", amount = arrayListOf("1/2 taza de vodka", "1/2 taza de frambuesas", "Jugo de 1 limón", "1 cucharadita de azúcar")),
                    Recipe(name = "Sandwiches Club", image = R.drawable.sandwichesclub, category = "Evento", subcategory1 = "Picnic", subcategory2 = "Sandwiches Club", ingredients = arrayListOf("Pan de molde", "Pollo", "Bacon", "Lechuga", "Tomate", "Mayonesa"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "30 minutos", quantity = "4 sandwiches", amount = arrayListOf("8 rebanadas de pan de molde", "200g de pollo", "4 rebanadas de bacon", "Hoja de lechuga", "2 tomates", "4 cucharadas de mayonesa")),
                    Recipe(name = "Ensalada César", image = R.drawable.ensaladacesar, category = "Evento", subcategory1 = "Picnic", subcategory2 = "Ensalada César", ingredients = arrayListOf("Lechuga", "Pollo", "Queso parmesano", "Aderezo César", "Croutons"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "20 minutos", quantity = "4 personas", amount = arrayListOf("1 lechuga romana", "200g de pechuga de pollo", "1/2 taza de queso parmesano", "1/4 taza de aderezo César", "Croutons al gusto")),
                    Recipe(name = "Wraps de Pollo", image = R.drawable.wrapdepollo, category = "Evento", subcategory1 = "Picnic", subcategory2 = "Wraps de Pollo", ingredients = arrayListOf("Pollo a la parrilla", "Tortillas", "Lechuga", "Tomate", "Mayonesa", "Aguacate"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "20 minutos", quantity = "4 wraps", amount = arrayListOf("200g de pollo a la parrilla", "4 tortillas", "Hoja de lechuga", "2 tomates", "4 cucharadas de mayonesa", "1 aguacate")),
                    Recipe(name = "Lemonade", image = R.drawable.lemonade, category = "Evento", subcategory1 = "Picnic", subcategory2 = "Lemonade", ingredients = arrayListOf("Limón", "Agua", "Azúcar", "Hielo"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "10 minutos", quantity = "4 personas", amount = arrayListOf("4 limones", "4 tazas de agua", "1/2 taza de azúcar", "Hielo al gusto")),
                    Recipe(name = "Cocteles Variados", image = R.drawable.coctelesvariados, category = "Evento", subcategory1 = "Fiesta de Año Nuevo", subcategory2 = "Bebidas", ingredients = arrayListOf("Vodka", "Ron", "Ginebra", "Jugo de naranja", "Hielo"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "20 minutos", quantity = "6 personas", amount = arrayListOf("100ml de vodka", "100ml de ron", "100ml de ginebra", "1 taza de jugo de naranja", "Hielo al gusto")),
                    Recipe(name = "Canapés", image = R.drawable.canapes, category = "Evento", subcategory1 = "Fiesta de Año Nuevo", subcategory2 = "Canapés", ingredients = arrayListOf("Pan de canapé", "Queso crema", "Salmón ahumado", "Caviar", "Pepino"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "15 minutos", quantity = "12 unidades", amount = arrayListOf("12 rebanadas de pan de canapé", "100g de queso crema", "100g de salmón ahumado", "30g de caviar", "1 pepino")),
                    Recipe(name = "Mini Quiches", image = R.drawable.miniquiches, category = "Evento", subcategory1 = "Fiesta de Año Nuevo", subcategory2 = "Canapés", ingredients = arrayListOf("Masa para quiche", "Huevos", "Queso", "Espinacas", "Bacon"), isFavorite = false, isCreatedByUser = false, dificulty = "Media", time = "30 minutos", quantity = "12 unidades", amount = arrayListOf("1 paquete de masa para quiche", "3 huevos", "100g de queso", "1 taza de espinacas", "50g de bacon")),
                    Recipe(name = "Tarta de Santiago", image = R.drawable.tartadesantiago, category = "Evento", subcategory1 = "Fiesta de Año Nuevo", subcategory2 = "Canapés", ingredients = arrayListOf("Almendras", "Huevo", "Azúcar", "Limón", "Harina"), isFavorite = false, isCreatedByUser = false, dificulty = "Alta", time = "1 hora", quantity = "8 personas", amount = arrayListOf("200g de almendras", "2 huevos", "150g de azúcar", "1 limón", "100g de harina")),
                    Recipe(name = "Fondue de Chocolate", image = R.drawable.fonduedechocolate, category = "Evento", subcategory1 = "Fiesta de Año Nuevo", subcategory2 = "Canapés", ingredients = arrayListOf("Chocolate negro", "Crema de leche", "Frutas", "Malvaviscos"), isFavorite = false, isCreatedByUser = false, dificulty = "Baja", time = "20 minutos", quantity = "4 personas", amount = arrayListOf("200g de chocolate negro", "100ml de crema de leche", "Frutas al gusto", "Malvaviscos al gusto"))
                )

                dbAccess.recipeDao().insertarRecetas(recipes)

                lifecycleScope.launch {
                    val randomRecipe = dbAccess.recipeDao().obtenerRecetaAleatoria()
                    binding.nameRecipe.text = randomRecipe.name
                    binding.imageRecipe.setImageResource(randomRecipe.image)
                    binding.categoryName.text = randomRecipe.category
                    binding.subcategoryName.text = randomRecipe.subcategory1

                    binding.buttonSeeRecipe.setOnClickListener {
                        val intentRecipe = Intent(this@MenuActivity, RecipeActivity::class.java)
                        intentRecipe.putExtra(ID_PASO_RECETA, randomRecipe)
                        startActivity(intentRecipe)
                    }
                }
                setUp()

            } else {
                lifecycleScope.launch {
                    lifecycleScope.launch {
                        val randomRecipe = dbAccess.recipeDao().obtenerRecetaAleatoria()
                        binding.nameRecipe.text = randomRecipe.name
                        binding.imageRecipe.setImageResource(randomRecipe.image)
                        binding.categoryName.text = randomRecipe.category
                        binding.subcategoryName.text = randomRecipe.subcategory1

                        binding.buttonSeeRecipe.setOnClickListener {
                            val intentRecipe = Intent(this@MenuActivity, RecipeActivity::class.java)
                            intentRecipe.putExtra(ID_PASO_RECETA, randomRecipe)
                            startActivity(intentRecipe)
                        }
                    }
                    setUp()
                }

            }
        }


        binding.buttonCreateRecipe.setOnClickListener{
            val intentCreateRecipe = Intent(this, CreateRecipeActivity::class.java)
            startActivity(intentCreateRecipe)
        }
        binding.recetIcon.setOnClickListener{
            val intentrecetActivity = Intent(this, GuardadoActivity::class.java)
            startActivity(intentrecetActivity)
        }


        binding.categoryIcon.setOnClickListener{
            val intentCategory = Intent(this, CategoriesActivity::class.java)
            startActivity(intentCategory)
        }

        binding.userIcon.setOnClickListener{
            val intentUser = Intent(this, UserScreenActivity::class.java)
            startActivity(intentUser)
        }

        binding.buttonCreateRecipe.setOnClickListener{
            val intentCreateRecipe = Intent(this, CreateRecipeActivity::class.java)
            startActivity(intentCreateRecipe)
        }

        binding.imageButtonSearch.setOnClickListener{
            val intentSearch = Intent(this, SearchRecipeActivity::class.java)
            startActivity(intentSearch)
        }
        //setUpRecyclerView()
    }
    private fun navigateToHome() {
        startActivity(Intent(this, MenuActivity::class.java))
        finish()
    }

    fun setUp(){
        lifecycleScope.launch {
            val subcategories = listOf(
                Subcategory(name = "Italia", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Italia"), category = "Paises"),
                Subcategory(name = "México", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("México"), category = "Paises"),
                Subcategory(name = "Japón", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Japón"), category = "Paises"),
                Subcategory(name = "Bolivia", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Bolivia"), category = "Paises"),
                Subcategory(name = "Francia", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Francia"), category = "Paises"),
                Subcategory(name = "Desayunos", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Desayunos"), category = "Tipo de comida"),
                Subcategory(name = "Entradas", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Entradas"), category = "Tipo de comida"),
                Subcategory(name = "Platos Principales", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Platos Principales"), category = "Tipo de comida"),
                Subcategory(name = "Postres", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Postres"), category = "Tipo de comida"),
                Subcategory(name = "Bebidas", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Bebidas"), category = "Tipo de comida"),
                Subcategory(name = "Vegetariana", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Vegetariana"), category = "Estilo de alimentación"),
                Subcategory(name = "Vegana", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Vegana"), category = "Estilo de alimentación"),
                Subcategory(name = "Sin Gluten", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Sin Gluten"), category = "Estilo de alimentación"),
                Subcategory(name = "Low Carb", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Low Carb"), category = "Estilo de alimentación"),
                Subcategory(name = "Alta en Proteína", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Alta en Proteína"), category = "Estilo de alimentación"),
                Subcategory(name = "Al Horno", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Al Horno"), category = "Metodo de preparación"),
                Subcategory(name = "A la Parrilla", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("A la Parrilla"), category = "Metodo de preparación"),
                Subcategory(name = "Frituras", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Frituras"), category = "Metodo de preparación"),
                Subcategory(name = "En Crudo", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("En Crudo"), category = "Metodo de preparación"),
                Subcategory(name = "Sopa", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Sopa"), category = "Metodo de preparación"),
                Subcategory(name = "Cumpleaños", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Cumpleaños"), category = "Eventos"),
                Subcategory(name = "Navidad", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Navidad"), category = "Eventos"),
                Subcategory(name = "San Valentín", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("San Valentín"), category = "Eventos"),
                Subcategory(name = "Picnic", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Picnic"), category = "Eventos"),
                Subcategory(name = "Año nuevo", recipes = dbAccess.recipeDao().obtenerPorSubcategoria("Año nuevo"), category = "Eventos"))

            recyclerSubcategoryAdapter.addDataToList(subcategories)
            binding.recyclerViewSubcategories.apply {
                layoutManager =
                    LinearLayoutManager(context, LinearLayoutManager.VERTICAL, false)
                adapter = recyclerSubcategoryAdapter
            }
        }

        binding.userIcon.setOnClickListener{
            val intentUserActivity = Intent(this, UserScreenActivity::class.java)
            startActivity(intentUserActivity)
        }

    }

}